### PR TITLE
Add Laravel 8 & Socialite 5 support

### PR DESCRIPTION
**Pull request by MrMicky-FR**
Add Laravel 8 & Socialite 5 support and add message to `InvalidStateException` to simplify debug (also just removed `illuminate/contracts` because it's already required by `illuminate/support`)

### CODE REVIEW

**Comment by MrMicky-FR** [comment]
Sorry, I didn't saw the PR #6 was just opened 😅

**Comment by ShawnCZek** [comment]
No worries. Thank you for the contribution! I will check whether I can remove Laravel Contracts later on.

Also, the exception might be useful to add. On the other hand, should it also be thrown when the request is not valid? And when the Steam ID is 0, is such a piece of information even useful? Though, a custom exception message can be added. Feel free to create a pull request for it.

**Comment by MrMicky-FR** [comment]
I put it in case an invalid SteamID was passed in the request (I guess theoretically it shouldn't happen). But otherwise yes when the Steam ID is 0 it's useless, so maybe it would be better to not have the Steam ID in the message ?

**Comment by ShawnCZek** [comment]
Yes, as I mentioned above, a custom exception message can be added for sure. Maybe mentioning that the validation was not successful. Or split both checks (from the condition statement) and throw an exception with a custom error message for both of them.

**Pull request closed without merging**
